spring:
  application:
    name: edustream-user-ms
    # Application name Configuration


  config:
    import: configserver:http://localhost:8888

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    # This will default to 'local' if SPRING_PROFILES_ACTIVE is not set in the environment

  datasource:
    url: jdbc:postgresql://localhost:5432/edu_stream_course
    driver-class-name: org.postgresql.Driver
    # Set the database connection properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    # JPA/Hibernate Configuration

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100
      # Pagination configuration


management:
  endpoints:
    web:
      exposure:
        include: "*"
    #Actuator configuration

